[package]
name = "dp-school"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fib"
path = "bin/fib.rs"

[[bin]]
name = "trib"
path = "bin/trib.rs"

[[bin]]
name = "fib_last"
path = "bin/fib_last.rs"
